### ISSUE TITLE
`return` keyword highlighted in CHECK comments

### ISSUE THREAD

**Issue by phoenix-meadowlark** [mlir-visualizer/mlir-vscode#2]
The `return` keyword is currently highlighted in any check comments that match the following formats:
```
// CHECK *:.* return .*
// CHECK-[a-zA-Z0-9]+ *:.* return .*
// CHECK-textand0123   :text & punct return text & punct
```

**Comment by phoenix-meadowlark** [comment]
<img width="581" alt="Screen Shot 2020-04-14 at 12 36 07 PM" src="https://user-images.githubusercontent.com/40036383/79266553-97f12900-7e4c-11ea-8826-4de205ffc0f5.png">

**Comment by LuPri** [comment]
Since a lot of CHECK comments contain code, we highlight the keywords within those comments. Since return is a keyword, it gets highlighted. In a future commit, I have changed so that only CHECK and CHECK-[word characters]* will make the keywords in comment be highlighted.
